name: Build & Deploy Travel-Planner to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend   # build inside your frontend folder

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'   # safe cache; no lockfile path needed

      # Install deps; if there's no lockfile, fall back to npm install
      - name: Install dependencies
        run: npm ci || npm install

      # Build: 
      #  - PUBLIC_URL helps Create React App under /Travel-Planner/
      #  - -- --base=/Travel-Planner/ helps Vite projects
      - name: Build the site
        env:
          PUBLIC_URL: /Travel-Planner/
          CI: "false"
        run: |
          npm run build -- --base=/Travel-Planner/ || npm run build

      # See what was produced (useful if something fails)
      - name: Show build output
        run: |
          ls -lah
          if [ -d "dist" ]; then echo "Found dist/"; ls -lah dist; fi
          if [ -d "build" ]; then echo "Found build/"; ls -lah build; fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Upload whichever folder exists (Vite: dist/, CRA: build/)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: |
            frontend/dist
            frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
